spring:
  application:
    name: marketpulse
  datasource:
    url: jdbc:postgresql://localhost:5432/mi-postgres
    username: admin
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true